### ISSUE TITLE
No logs.

### ISSUE THREAD

**Issue by alvarlagerlof** [subsoap/log#2]
I can't manage to get any logs from your lib. I've included it and fetched libraries, but it's nor printing anything. 

This is my code.
log = require("log.log")
log.set_appname("Platformer")
log.d("foobar")

Other things in the block run just fine. And i also get no error from from the lib?

What have I done wrong?

**Comment by alvarlagerlof** [comment]
Had to do log.toggle_print(). Shouldn't that be on as default.

But this is not changing the colors?
![image](https://user-images.githubusercontent.com/14835120/41508006-df874500-723d-11e8-97dc-dbf3992bccba.png)

**Comment by subsoap** [comment]
Printing to console isn't enabled by default at the moment, but saving the log to files is. I'll maybe set it to enabled by default.

I tested trying to use color codes for the printed output but didn't get it to work yet. I'll ask Defold team if it's possible.

**Comment by alvarlagerlof** [comment]
Or atleast make it more clear that you have to turn it on to see in the console. 

Yeah please talk to them. Colors would be a killer feature. And if you could replace it saying debug in the begining then it's really something else would also be really nice.

**Comment by subsoap** [comment]
I've updated readme, and made requests to Defold team for features so I can change colors. Until they add these features, there's nothing I can do to add colors so I'll close this for now.
